profile:
  m3fc_position: core
  accel_axis: z
  ignition_accel: 25
  burnout_timeout: 1.8
  apogee_timeout: 30
  main_altitude: 250
  main_timeout: 60
  land_timeout: 600

pyros:
  pyro_1_usage: dartsep
  pyro_1_type: metron
  pyro_2_usage: drogue
  pyro_2_type: metron
  pyro_3_usage: main
  pyro_3_type: metron
  pyro_4_usage: unused
  pyro_4_type: none

accel_cal_x:
  scale: 0.0039
  offset: -4

accel_cal_y:
  scale: 0.0039
  offset: -4

accel_cal_z:
  scale: 0.00404944
  offset: -23.4957

radio_freq: 869600000
